# Generated by Django 3.2.4 on 2021-06-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default.img', upload_to='book_images/'),
        ),
    ]
